name: 'Pull request'
on:
  # Running on push is necessary as a commit resets
  # all checks and so they need to run again.
  push:
    branches-ignore:
      - master
  pull_request:
    types:
      - opened
      - edited

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@feature/WIP-support
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
